### ISSUE TITLE
怎么编译？

### ISSUE THREAD

**Issue by hzr12** [seiuna/skymatrix#1]
> Task :compileJava
D:\mc fabric mod\skymatrix-main\skymatrix-main\src\main\java\cn\seiua\skymatrix\client\module\modules\life\FarmingHelper.java:3: ����: �����baritone.api������
import baritone.api.BaritoneAPI;
                   ^
D:\mc fabric mod\skymatrix-main\skymatrix-main\src\main\java\cn\seiua\skymatrix\client\waypoint\Waypoint.java:3: ����: �����baritone.api������
import baritone.api.BaritoneAPI;
                   ^
D:\mc fabric mod\skymatrix-main\skymatrix-main\src\main\java\cn\seiua\skymatrix\client\waypoint\Waypoint.java:4: ����: �����baritone.api.pathing.goals������
import baritone.api.pathing.goals.GoalBlock;
                                 ^
D:\mc fabric mod\skymatrix-main\skymatrix-main\src\main\java\cn\seiua\skymatrix\client\waypoint\WPProcess.java:3: ����: �����baritone.api������
import baritone.api.BaritoneAPI;
                   ^
D:\mc fabric mod\skymatrix-main\skymatrix-main\src\main\java\cn\seiua\skymatrix\client\waypoint\WPProcess.java:4: ����: �����baritone.api.pathing.goals������
import baritone.api.pathing.goals.GoalBlock;
                                 ^
5 ������

> Task :compileJava FAILED

**Comment by hzr12** [comment]
编译一直报错

**Comment by hzr12** [comment]
cmd去编译时
Task :compileJava
D:\mc fabric mod\skymatrix\src\main\java\cn\seiua\skymatrix\client\module\modules\life\FarmingHelper.java:3: 閿欒: 绋嬪簭鍖卋aritone.api涓嶅瓨鍦?
                          import baritone.api.BaritoneAPI;
                   ^
D:\mc fabric mod\skymatrix\src\main\java\cn\seiua\skymatrix\client\waypoint\Waypoint.java:3: 閿欒: 绋嬪簭鍖卋aritone.api涓嶅瓨鍦?
          import baritone.api.BaritoneAPI;
                   ^
D:\mc fabric mod\skymatrix\src\main\java\cn\seiua\skymatrix\client\waypoint\Waypypoint.java:4: 閿欒: 绋嬪簭鍖卋aritone.api.pathing.goals涓嶅瓨鍦?
                          import baritone.api.pathing.goals.GoalBlock;
                                 ^
D:\mc fabric mod\skymatrix\src\main\java\cn\seiua\skymatrix\client\waypoint\WPProcess.java:3: 閿欒: 绋嬪簭鍖卋aritone.api涓嶅瓨鍦?
           import baritone.api.BaritoneAPI;
                   ^
D:\mc fabric mod\skymatrix\src\main\java\cn\seiua\skymatrix\client\waypoint\WPProcess.java:4: 閿欒: 绋嬪簭鍖卋aritone.api.pathing.goals涓嶅瓨鍦?
                         import baritone.api.pathithing.goals.GoalBlock;
                                 ^
5 涓敊璇?
<
> Task :compileJava FAILED
B
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
1 actionable task: 1 executed

**Comment by seiuna** [comment]
加群 849749832
